import React, { useState } from 'react';
import { AccessCodeDetailsModal, type AccessCodeDetailData } from './AccessCodeDetailsModal';

interface AccessCodeItem {
  id: string;
  guestName: string;
  code: string;
  generatedBy: string;
  status: 'Active' | 'Expired' | 'Revoked';
  timeAgo: 'today' | 'this_week';
  date: string;
}

const initialAccessCodes: AccessCodeItem[] = [
  { id: '1', guestName: 'Kamsy', code: '005UHJ9', generatedBy: 'Teni Olayiwola', status: 'Active', timeAgo: 'today', date: '08/08/2023' },
  { id: '2', guestName: 'Kamsy', code: '005UHJ8', generatedBy: 'Teni Olayiwola', status: 'Active', timeAgo: 'today', date: '08/08/2023' },
  { id: '3', guestName: 'Kamsy', code: '005UHJ7', generatedBy: 'Teni Olayiwola', status: 'Active', timeAgo: 'today', date: '08/08/2023' },
  { id: '4', guestName: 'Kamsy', code: '005UHJ6', generatedBy: 'Teni Olayiwola', status: 'Active', timeAgo: 'today', date: '08/08/2023' },
  { id: '5', guestName: 'Kamsy', code: '005UHJ5', generatedBy: 'Teni Olayiwola', status: 'Active', timeAgo: 'today', date: '08/08/2023' },
  { id: '6', guestName: 'Kamsy', code: '005UHJ4', generatedBy: 'Teni Olayiwola', status: 'Expired', timeAgo: 'this_week', date: '08/08/2023' },
  { id: '7', guestName: 'Kamsy', code: '005UHJ3', generatedBy: 'Teni Olayiwola', status: 'Expired', timeAgo: 'this_week', date: '08/08/2023' },
  { id: '8', guestName: 'Kamsy', code: '005UHJ2', generatedBy: 'Teni Olayiwola', status: 'Expired', timeAgo: 'this_week', date: '08/08/2023' },
];

export const AccessCodeScreen: React.FC = () => {
  const [accessCodes, setAccessCodes] = useState<AccessCodeItem[]>(initialAccessCodes);
  const [selectedItem, setSelectedItem] = useState<AccessCodeItem | null>(null);

  const handleOpenDetails = (item: AccessCodeItem) => {
    setSelectedItem(item);
  };

  const handleCloseModal = () => {
    setSelectedItem(null);
  };

  const handleRevokeSuccess = (id: string) => {
    setAccessCodes((prev) =>
      prev.map((code) => (code.id === id ? { ...code, status: 'Revoked' } : code))
    );
  };

  const todayCodes = accessCodes.filter((item) => item.timeAgo === 'today');
  const thisWeekCodes = accessCodes.filter((item) => item.timeAgo === 'this_week');

  const detailData: AccessCodeDetailData | null = selectedItem
    ? {
        id: selectedItem.id,
        code: selectedItem.code,
        generatedBy: selectedItem.generatedBy,
        generatedFor: `${selectedItem.guestName} Okafor`,
        status: selectedItem.status,
        date: selectedItem.date,
      }
    : null;

  return (
    <div style={styles.mobileShell}>
      <div style={styles.container}>
        {!selectedItem ? (
          <>
            {/* Header / Brand */}
            <div style={styles.topBar}>
              <div style={styles.brandWrapper}>
                <img src="/splash/gateshark-logo-green.png" alt="GateShark Emblem" style={styles.brandIcon} />
                <span style={styles.brandName}>GateShark</span>
              </div>
            </div>

            {/* Banner Card Header */}
            <div style={styles.bannerCard}>
              <h2 style={styles.bannerTitle}>Access Codes</h2>
              <p style={styles.bannerSubtitle}>See all codes generated by you</p>
            </div>

            {/* List Body */}
            <div style={styles.listBody}>
              {/* Today Section */}
              <div style={styles.sectionGroup}>
                <h3 style={styles.sectionHeader}>Today</h3>
                <hr style={styles.sectionDivider} />

                {todayCodes.map((item) => (
                  <div key={item.id} style={styles.codeItemRow}>
                    <div style={styles.leftInfo}>
                      <span
                        style={item.status === 'Active' ? styles.greenDot : styles.redDot}
                      />
                      <span style={styles.inviteText}>
                        You invited <strong>{item.guestName}</strong>
                      </span>
                    </div>
                    <button style={styles.viewDetailsBtn} onClick={() => handleOpenDetails(item)}>
                      View details
                    </button>
                  </div>
                ))}
              </div>

              {/* This Week Section */}
              <div style={styles.sectionGroup}>
                <h3 style={styles.sectionHeader}>This week</h3>
                <hr style={styles.sectionDivider} />

                {thisWeekCodes.map((item) => (
                  <div key={item.id} style={styles.codeItemRow}>
                    <div style={styles.leftInfo}>
                      <span
                        style={item.status === 'Active' ? styles.greenDot : styles.redDot}
                      />
                      <span style={styles.inviteText}>
                        You invited <strong>{item.guestName}</strong>
                      </span>
                    </div>
                    <button style={styles.viewDetailsBtn} onClick={() => handleOpenDetails(item)}>
                      View details
                    </button>
                  </div>
                ))}
              </div>
            </div>
          </>
        ) : (
          detailData && (
            <AccessCodeDetailsModal
              data={detailData}
              onClose={handleCloseModal}
              onRevokeSuccess={handleRevokeSuccess}
              onReinvite={(item) => {
                alert(`Re-invited ${item.generatedFor} successfully!`);
                handleCloseModal();
              }}
            />
          )
        )}
      </div>
    </div>
  );
};

const styles: Record<string, React.CSSProperties> = {
  mobileShell: {
    minHeight: '100vh',
    backgroundColor: '#ffffff',
    color: '#0f172a',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'flex-start',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    overflowY: 'auto',
  },
  container: {
    width: '100%',
    maxWidth: '440px',
    minHeight: '100vh',
    padding: '20px 24px 100px',
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    backgroundColor: '#ffffff',
  },
  topBar: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 'calc(10px + env(safe-area-inset-top, 0px))',
    marginBottom: '20px',
    width: '100%',
  },
  brandWrapper: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
  },
  brandIcon: {
    width: '28px',
    height: '32px',
    objectFit: 'contain',
  },
  brandName: {
    fontSize: '22px',
    fontWeight: '700',
    color: '#1e293b',
    letterSpacing: '-0.4px',
  },
  bannerCard: {
    backgroundImage: 'url("/invite/invite.svg")',
    backgroundSize: 'cover',
    backgroundPosition: 'center',
    borderRadius: '16px',
    padding: '24px 20px',
    textAlign: 'left',
    color: '#ffffff',
    marginBottom: '28px',
    boxShadow: '0 8px 20px rgba(0, 0, 0, 0.15)',
  },
  bannerTitle: {
    fontSize: '22px',
    fontWeight: '700',
    margin: '0 0 4px 0',
  },
  bannerSubtitle: {
    fontSize: '13px',
    color: '#e2e8f0',
    margin: 0,
    opacity: 0.9,
  },
  listBody: {
    display: 'flex',
    flexDirection: 'column',
    gap: '28px',
    width: '100%',
    textAlign: 'left',
  },
  sectionGroup: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
  },
  sectionHeader: {
    fontSize: '18px',
    fontWeight: '700',
    color: '#0f172a',
    margin: '0 0 6px 0',
  },
  sectionDivider: {
    border: 'none',
    borderTop: '1px solid #e2e8f0',
    margin: '0 0 16px 0',
  },
  codeItemRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '12px 0',
    width: '100%',
  },
  leftInfo: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
  },
  greenDot: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    backgroundColor: '#22c55e',
    display: 'inline-block',
  },
  redDot: {
    width: '10px',
    height: '10px',
    borderRadius: '50%',
    backgroundColor: '#dc2626',
    display: 'inline-block',
  },
  inviteText: {
    fontSize: '15px',
    color: '#334155',
    fontWeight: '400',
  },
  viewDetailsBtn: {
    background: 'none',
    border: 'none',
    color: '#64748b',
    fontSize: '14px',
    fontWeight: '500',
    cursor: 'pointer',
    padding: '4px',
  },
};
