import React, { useState } from 'react';

export interface AccessCodeDetailData {
  id: string;
  code: string;
  generatedBy: string;
  generatedFor: string;
  status: 'Active' | 'Expired' | 'Revoked';
  date: string;
}

interface AccessCodeDetailsModalProps {
  data: AccessCodeDetailData;
  onClose: () => void;
  onReinvite?: (data: AccessCodeDetailData) => void;
  onRevokeSuccess?: (id: string) => void;
}

export const AccessCodeDetailsModal: React.FC<AccessCodeDetailsModalProps> = ({
  data,
  onClose,
  onReinvite,
  onRevokeSuccess,
}) => {
  const [currentStatus, setCurrentStatus] = useState<'Active' | 'Expired' | 'Revoked'>(data.status);
  const [isRevokedSuccess, setIsRevokedSuccess] = useState(false);

  const handleRevoke = () => {
    setCurrentStatus('Revoked');
    setIsRevokedSuccess(true);
    if (onRevokeSuccess) {
      onRevokeSuccess(data.id);
    }
  };

  const handleReinvite = () => {
    if (onReinvite) {
      onReinvite(data);
    } else {
      alert(`Re-inviting ${data.generatedFor}...`);
    }
  };

  return (
    <div style={styles.modalBody}>
      {/* VIEW 3: Revoked Access Confirmation View */}
      {isRevokedSuccess ? (
        <div style={styles.revokedContainer}>
          <div style={styles.revokedIconCircle}>
            <span style={styles.revokedIconText}>✕</span>
          </div>
          <h2 style={styles.revokedTitle}>Access has been revoked!</h2>
          <p style={styles.revokedSubtitle}>
            A notification has been sent to estate security
          </p>
          <button style={styles.closeDoneBtn} onClick={onClose}>
            Done
          </button>
        </div>
      ) : (
        /* VIEW 1 & 2: Active or Expired Code Details Modal */
        <>
          {/* Header Bar */}
          <div style={styles.modalHeader}>
            <div style={styles.codeHeaderTitle}>
              Access Code: <strong style={styles.codeBold}>{data.code}</strong>
            </div>
            <button style={styles.closeBtn} onClick={onClose} aria-label="Close">
              ✕
            </button>
          </div>

          {/* Details Tab Line */}
          <div style={styles.tabBar}>
            <div style={styles.activeTabItem}>Details</div>
          </div>

          {/* Section Header */}
          <div style={styles.mainDetailsTitle}>MAIN DETAILS</div>

          {/* Fields Rows */}
          <div style={styles.detailsGroup}>
            <div style={styles.detailRow}>
              <span style={styles.label}>Code generated by</span>
              <strong style={styles.valText}>{data.generatedBy}</strong>
            </div>

            <div style={styles.detailRow}>
              <span style={styles.label}>Code generated for</span>
              <strong style={styles.valText}>{data.generatedFor}</strong>
            </div>

            <div style={styles.detailRow}>
              <span style={styles.label}>Status</span>
              <strong
                style={{
                  ...styles.valText,
                  color: currentStatus === 'Active' ? '#16a34a' : '#dc2626',
                }}
              >
                {currentStatus}
              </strong>
            </div>

            <div style={styles.detailRow}>
              <span style={styles.label}>Date</span>
              <strong style={styles.valText}>{data.date}</strong>
            </div>
          </div>

          {/* Action Button: Revoke Access (for Active) vs Re-invite (for Expired) */}
          <div style={styles.actionFooter}>
            {currentStatus === 'Active' ? (
              <button style={styles.revokeBtn} onClick={handleRevoke}>
                Revoke Access
              </button>
            ) : (
              <button style={styles.reinviteBtn} onClick={handleReinvite}>
                Re-invite
              </button>
            )}
          </div>
        </>
      )}
    </div>
  );
};

const styles: Record<string, React.CSSProperties> = {
  modalBody: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: '16px',
    padding: '10px 0 20px',
    boxSizing: 'border-box',
  },
  modalHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: '20px',
    padding: '0 4px',
  },
  codeHeaderTitle: {
    fontSize: '18px',
    color: '#0f172a',
  },
  codeBold: {
    fontSize: '22px',
    fontWeight: '800',
    color: '#0f172a',
    letterSpacing: '0.5px',
    marginLeft: '6px',
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    fontSize: '24px',
    color: '#285843',
    fontWeight: 'bold',
    cursor: 'pointer',
    padding: '4px',
  },
  tabBar: {
    display: 'flex',
    borderBottom: '1px solid #e2e8f0',
    marginBottom: '24px',
  },
  activeTabItem: {
    fontSize: '17px',
    fontWeight: '700',
    color: '#0f172a',
    paddingBottom: '10px',
    borderBottom: '2.5px solid #0f172a',
    marginRight: '20px',
  },
  mainDetailsTitle: {
    fontSize: '14px',
    fontWeight: '600',
    color: '#475569',
    letterSpacing: '0.5px',
    marginBottom: '20px',
    textAlign: 'left',
  },
  detailsGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
    marginBottom: '40px',
  },
  detailRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  label: {
    fontSize: '15px',
    color: '#94a3b8',
    fontWeight: '400',
  },
  valText: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#0f172a',
  },
  actionFooter: {
    display: 'flex',
    justifyContent: 'center',
    marginTop: '10px',
  },
  revokeBtn: {
    backgroundColor: '#ffffff',
    color: '#dc2626',
    border: '1px solid #cbd5e1',
    borderRadius: '12px',
    padding: '12px 32px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  reinviteBtn: {
    backgroundColor: '#ffffff',
    color: '#285843',
    border: '1px solid #cbd5e1',
    borderRadius: '12px',
    padding: '12px 36px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  revokedContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px 10px',
    textAlign: 'center',
  },
  revokedIconCircle: {
    width: '56px',
    height: '56px',
    borderRadius: '50%',
    backgroundColor: '#dc2626',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '20px',
  },
  revokedIconText: {
    color: '#ffffff',
    fontSize: '26px',
    fontWeight: 'bold',
  },
  revokedTitle: {
    fontSize: '22px',
    fontWeight: '700',
    color: '#dc2626',
    margin: '0 0 10px 0',
  },
  revokedSubtitle: {
    fontSize: '15px',
    color: '#0f172a',
    margin: '0 0 32px 0',
    lineHeight: '1.4',
    maxWidth: '300px',
  },
  closeDoneBtn: {
    backgroundColor: '#ffffff',
    color: '#0f172a',
    border: '1px solid #cbd5e1',
    borderRadius: '10px',
    padding: '10px 28px',
    fontSize: '15px',
    fontWeight: '600',
    cursor: 'pointer',
  },
};
