import React, { useState } from 'react';
import { type NotificationItem } from './NotificationScreen';

interface NotificationDetailModalProps {
  item: NotificationItem;
  onClose: () => void;
  onReinvite?: () => void;
  onRevokeAccess?: () => void;
}

export const NotificationDetailModal: React.FC<NotificationDetailModalProps> = ({
  item,
  onClose,
  onReinvite,
  onRevokeAccess,
}) => {
  const [revoked, setRevoked] = useState(false);

  const handleRevoke = () => {
    setRevoked(true);
    if (onRevokeAccess) onRevokeAccess();
  };

  const handleReinvite = () => {
    if (onReinvite) {
      onReinvite();
    } else {
      alert('Re-inviting guest...');
    }
  };

  return (
    <div style={styles.modalBody}>
      {/* Close Button Header */}
      <div style={styles.modalHeader}>
        <button style={styles.closeBtn} onClick={onClose} aria-label="Close">
          ✕
        </button>
      </div>

      {/* VIEW TYPE 1: Code Expiry Modal */}
      {item.category === 'expiry' && (
        <>
          <div style={styles.titleSection}>
            <span style={{ ...styles.categoryBadge, color: '#4338ca' }}>CODE EXPIRY:</span>
            <h2 style={styles.mainTitle}>This code expires in 1hr</h2>
          </div>

          <div style={styles.detailsList}>
            <div style={styles.detailRow}>
              <span style={styles.label}>Access code</span>
              <strong style={styles.valText}>{item.code || '005UHJ9'}</strong>
            </div>
            <div style={styles.detailRow}>
              <span style={styles.label}>Generated by</span>
              <strong style={styles.valText}>Teniola Olayiwola</strong>
            </div>
            <div style={styles.detailRow}>
              <span style={styles.label}>Guest name</span>
              <strong style={styles.valText}>Kamsy Okafor</strong>
            </div>
            <div style={styles.detailRow}>
              <span style={styles.label}>Time</span>
              <strong style={styles.valText}>01 : 00pm</strong>
            </div>
            <div style={styles.detailRow}>
              <span style={styles.label}>Date</span>
              <strong style={styles.valText}>08/08/2023</strong>
            </div>
            <div style={styles.detailRow}>
              <span style={styles.label}>Status</span>
              <strong style={{ ...styles.valText, color: '#16a34a' }}>Active</strong>
            </div>
          </div>

          <div style={styles.footerCenter}>
            <button style={styles.reinviteBtn} onClick={handleReinvite}>
              Re-invite
            </button>
          </div>
        </>
      )}

      {/* VIEW TYPE 2: Used Code Modal */}
      {(item.category === 'used' || item.category === 'error') && (
        <>
          <div style={styles.titleSection}>
            <h2 style={{ ...styles.categoryBadge, color: '#854d0e', fontSize: '18px' }}>
              USED CODE
            </h2>
          </div>

          <div style={styles.detailsList}>
            <div style={styles.detailRow}>
              <span style={styles.label}>Access code</span>
              <strong style={styles.valText}>{item.code || '005UHJ9'}</strong>
            </div>
            <div style={styles.detailRow}>
              <span style={styles.label}>Generated by</span>
              <strong style={styles.valText}>Teniola Olayiwola</strong>
            </div>
            <div style={styles.detailRow}>
              <span style={styles.label}>Guest name</span>
              <strong style={styles.valText}>Kamsy Okafor</strong>
            </div>
            <div style={styles.detailRow}>
              <span style={styles.label}>Time</span>
              <strong style={styles.valText}>01 : 00pm</strong>
            </div>
            <div style={styles.detailRow}>
              <span style={styles.label}>Date</span>
              <strong style={styles.valText}>08/08/2023</strong>
            </div>
            <div style={styles.detailRow}>
              <span style={styles.label}>Status</span>
              <strong style={{ ...styles.valText, color: '#dc2626' }}>Expired</strong>
            </div>
          </div>

          <div style={styles.footerCenter}>
            <button style={styles.reinviteBtn} onClick={handleReinvite}>
              Re-invite
            </button>
          </div>
        </>
      )}

      {/* VIEW TYPE 3: Visitor Arrived Modal */}
      {item.category === 'visitor' && (
        <>
          {revoked ? (
            <div style={styles.revokedContainer}>
              <div style={styles.revokedIconCircle}>
                <span style={styles.revokedIconText}>✕</span>
              </div>
              <h2 style={styles.revokedTitle}>Access has been revoked!</h2>
              <p style={styles.revokedSubtitle}>A notification has been sent to estate security</p>
              <button style={styles.closeDoneBtn} onClick={onClose}>
                Done
              </button>
            </div>
          ) : (
            <>
              <div style={styles.titleSection}>
                <h2 style={{ ...styles.mainTitle, color: '#285843', fontSize: '20px', lineHeight: '1.4' }}>
                  Kamsy Okafor has arrived and has checked in at Ladipo Estate.
                </h2>
              </div>

              <div style={{ ...styles.detailsList, marginTop: '24px' }}>
                <div style={styles.detailRow}>
                  <span style={styles.label}>Access code</span>
                  <strong style={styles.valText}>{item.code || '005UHJ9'}</strong>
                </div>
                <div style={styles.detailRow}>
                  <span style={styles.label}>Time</span>
                  <strong style={styles.valText}>01 : 00pm</strong>
                </div>
                <div style={styles.detailRow}>
                  <span style={styles.label}>Date</span>
                  <strong style={styles.valText}>08/08/2023</strong>
                </div>
                <div style={styles.detailRow}>
                  <span style={styles.label}>Status</span>
                  <strong style={{ ...styles.valText, color: '#16a34a' }}>Active</strong>
                </div>
              </div>

              <div style={styles.footerAlertRow}>
                <span style={styles.alertNoteText}>Not authorized by you? Alert security</span>
                <button style={styles.revokeRedBtn} onClick={handleRevoke}>
                  Revoke access
                </button>
              </div>
            </>
          )}
        </>
      )}

      {/* VIEW TYPE 4: Account Suspended Modal */}
      {item.category === 'suspended' && (
        <>
          <div style={styles.titleSection}>
            <h2 style={{ ...styles.categoryBadge, color: '#dc2626', fontSize: '20px' }}>
              ACCOUNT SUSPENDED
            </h2>
            <p style={{ ...styles.mainTitle, fontSize: '15px', color: '#475569', marginTop: '8px', lineHeight: '1.5' }}>
              Your account has been suspended by estate management. Please contact administration for resolution.
            </p>
          </div>

          <div style={styles.detailsList}>
            <div style={styles.detailRow}>
              <span style={styles.label}>Status</span>
              <strong style={{ ...styles.valText, color: '#dc2626' }}>Suspended</strong>
            </div>
            <div style={styles.detailRow}>
              <span style={styles.label}>Time</span>
              <strong style={styles.valText}>{item.time}</strong>
            </div>
          </div>

          <div style={styles.footerCenter}>
            <button
              style={{ ...styles.reinviteBtn, color: '#dc2626', borderColor: '#fca5a5' }}
              onClick={() => alert('Connecting to GateShark Estate Administration...')}
            >
              Contact Admin
            </button>
          </div>
        </>
      )}
    </div>
  );
};

const styles: Record<string, React.CSSProperties> = {
  modalBody: {
    display: 'flex',
    flexDirection: 'column',
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: '16px',
    padding: '10px 0 20px',
    boxSizing: 'border-box',
    textAlign: 'left',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'flex-end',
    marginBottom: '10px',
    width: '100%',
  },
  closeBtn: {
    background: 'none',
    border: 'none',
    fontSize: '24px',
    color: '#285843',
    fontWeight: 'bold',
    cursor: 'pointer',
    padding: '4px',
  },
  titleSection: {
    marginBottom: '24px',
    padding: '0 4px',
  },
  categoryBadge: {
    fontSize: '16px',
    fontWeight: '800',
    letterSpacing: '0.5px',
    display: 'block',
    marginBottom: '6px',
  },
  mainTitle: {
    fontSize: '22px',
    fontWeight: '800',
    color: '#0f172a',
    margin: 0,
    letterSpacing: '-0.3px',
  },
  detailsList: {
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    marginBottom: '36px',
  },
  detailRow: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingBottom: '12px',
    borderBottom: '1px solid #f1f5f9',
  },
  label: {
    fontSize: '15px',
    color: '#64748b',
    fontWeight: '400',
  },
  valText: {
    fontSize: '16px',
    fontWeight: '700',
    color: '#0f172a',
  },
  footerCenter: {
    display: 'flex',
    justifyContent: 'center',
    marginTop: '10px',
  },
  reinviteBtn: {
    backgroundColor: '#ffffff',
    color: '#285843',
    border: '1px solid #cbd5e1',
    borderRadius: '10px',
    padding: '12px 36px',
    fontSize: '16px',
    fontWeight: '600',
    cursor: 'pointer',
  },
  footerAlertRow: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: '20px',
    gap: '12px',
  },
  alertNoteText: {
    fontSize: '14px',
    fontWeight: '700',
    color: '#0f172a',
  },
  revokeRedBtn: {
    backgroundColor: '#ffffff',
    color: '#dc2626',
    border: '1px solid #cbd5e1',
    borderRadius: '8px',
    padding: '10px 18px',
    fontSize: '14px',
    fontWeight: '600',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
  },
  revokedContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '40px 10px',
    textAlign: 'center',
  },
  revokedIconCircle: {
    width: '56px',
    height: '56px',
    borderRadius: '50%',
    backgroundColor: '#dc2626',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: '20px',
  },
  revokedIconText: {
    color: '#ffffff',
    fontSize: '26px',
    fontWeight: 'bold',
  },
  revokedTitle: {
    fontSize: '22px',
    fontWeight: '700',
    color: '#dc2626',
    margin: '0 0 10px 0',
  },
  revokedSubtitle: {
    fontSize: '15px',
    color: '#0f172a',
    margin: '0 0 32px 0',
    lineHeight: '1.4',
    maxWidth: '300px',
  },
  closeDoneBtn: {
    backgroundColor: '#ffffff',
    color: '#0f172a',
    border: '1px solid #cbd5e1',
    borderRadius: '10px',
    padding: '10px 28px',
    fontSize: '15px',
    fontWeight: '600',
    cursor: 'pointer',
  },
};
